### ISSUE TITLE
Create simple blog

### ISSUE THREAD

**Issue by kenk11** [kenk11/ruby-blog-kenk11#1]
Follow video walkthrough (https://www.youtube.com/watch?edit=vd&v=tMUMD8I7eYc)
Create simple blog and push to heroku
/cc @coderschoolreview

**Comment by kenk11** [comment]
Done
/cc @coderschoolreview

**Comment by chug2k** [comment]
**Congratulations, Welcome to our Ruby on Rails course**! We will email you in a few moments with details about where the course will be held. Thank you for your work on creating a basic Ruby on Rails app. :tada:

In the future, doing the "optional" tasks will be very beneficial. Most real-world apps will have a navbar, filtering, and and search, so learning how to do them will help you build better, more full-featured applications. For a first step, I'd recommend you read [about validations in ActiveRecord](http://guides.rubyonrails.org/active_record_validations.html) for a peek into some cool features from Rails & ActiveRecord. 

Sincerely,
PC Repair Man
